package com.square.jobs.conf

object DataJson {

  val ST_DAY =
    """
      |{
      |	"id": "",
      |	"app_code": "redbonus",
      |	"owner_code": "",
      |	"create_date": "0000-00-00 00:00:00",
      |	"user_flag": 0,
      |	"regi_user_count": 0,
      |	"regi_user_count_all": 0,
      |	"recharge_user_count": 0,
      |	"recharge_count": 0,
      |	"first_recharge_count": 0,
      |	"second_recharge_count": 0,
      |	"renewal_recharge_count": 0,
      |	"recharge_money": 0,
      |	"first_recharge_money": 0,
      |	"second_recharge_money": 0,
      |	"renewal_recharge_money": 0,
      |	"recharge_user_count_1": 0,
      |	"recharge_count_1": 0,
      |	"recharge_money_1": 0,
      |	"recharge_user_count_2": 0,
      |	"recharge_count_2": 0,
      |	"recharge_money_2": 0,
      |	"recharge_user_count_3": 0,
      |	"recharge_count_3": 0,
      |	"recharge_money_3": 0,
      |	"cash_count": 0,
      |	"cash_user_count": 0,
      |	"cash_money": 0,
      |	"active_user_count": 0,
      |	"user_profit": 0,
      |	"final_balance": 0,
      |	"initial_balance": 0,
      |	"sumall_40": 0,
      |	"sumall_36": 0,
      |	"sumall_37": 0,
      |	"sumall_19": 0,
      |	"sumall_20": 0,
      |	"sumall_21": 0,
      |	"sumall_22": 0,
      |	"sumall_23": 0,
      |	"sumall_16": 0,
      |	"sumall_27": 0,
      |	"sumall_28": 0,
      |	"sumall_30": 0,
      |	"sumall_43": 0,
      |	"sumall_32": 0,
      |	"sumall_44": 0,
      |	"sumall_45": 0,
      |	"sumall_8": 0,
      |	"sumall_31": 0,
      |	"sumall_9": 0,
      |	"sumall_38": 0,
      |	"sumall_7": 0,
      |	"count_id_40": 0,
      |	"count_id_36": 0,
      |	"count_id_37": 0,
      |	"count_id_19": 0,
      |	"count_id_20": 0,
      |	"count_id_21": 0,
      |	"count_id_22": 0,
      |	"count_id_23": 0,
      |	"count_id_16": 0,
      |	"count_id_27": 0,
      |	"count_id_28": 0,
      |	"count_id_30": 0,
      |	"count_id_43": 0,
      |	"count_id_32": 0,
      |	"count_id_44": 0,
      |	"count_id_45": 0,
      |	"count_id_8": 0,
      |	"count_id_31": 0,
      |	"count_id_9": 0,
      |	"count_id_38": 0,
      |	"count_id_7": 0,
      |	"count_40": 0,
      |	"count_36": 0,
      |	"count_37": 0,
      |	"count_19": 0,
      |	"count_20": 0,
      |	"count_21": 0,
      |	"count_22": 0,
      |	"count_23": 0,
      |	"count_16": 0,
      |	"count_27": 0,
      |	"count_28": 0,
      |	"count_30": 0,
      |	"count_43": 0,
      |	"count_32": 0,
      |	"count_44": 0,
      |	"count_45": 0,
      |	"count_8": 0,
      |	"count_31": 0,
      |	"count_9": 0,
      |	"count_38": 0,
      |	"count_7": 0,
      |	"reward_user_count": 0,
      |	"commision_user_count": 0,
      |	"niu_payout_money": 0,
      |	"niu_get_payout_money": 0,
      |	"lei_payout_money": 0,
      |	"lei_get_payout_money": 0,
      |	"lei_send_money": 0,
      |	"lei_grab_money": 0,
      |	"lei_send_count_user": 0,
      |	"lei_grab_count_user": 0,
      |	"lei_send_count": 0,
      |	"lei_grab_count": 0,
      |	"lei_game_count_user": 0,
      |	"niu_send_money": 0,
      |	"niu_grab_money": 0,
      |	"niu_send_count_user": 0,
      |	"niu_grab_count_user": 0,
      |	"niu_send_count": 0,
      |	"niu_grab_count": 0,
      |	"niu_game_count_user": 0,
      |	"jin_send_money": 0,
      |	"jin_grab_money": 0,
      |	"jin_send_count_user": 0,
      |	"jin_grab_count_user": 0,
      |	"jin_send_count": 0,
      |	"jin_grab_count": 0,
      |	"jin_game_count_user": 0,
      |	"niu_payout_money_in": 0,
      |	"niu_payout_money_out": 0,
      |	"lei_grab_money_out": 0,
      |	"lei_payout_money_death_in": 0,
      |	"lei_payout_money_other_in": 0,
      |	"lei_grab_money_death_in": 0,
      |	"lei_payout_money_death_out": 0,
      |	"lei_grab_money_other_in": 0,
      |	"lei_payout_money_other_out": 0,
      |	"jin_payout_money_out": 0,
      |	"jin_grab_money_in": 0,
      |	"reward_grab_money_in": 0,
      |	"reward_grab_money_out": 0,
      |	"increase_member_money_out": 0,
      |	"reduce_member_money_In": 0,
      |	"increase_in_money": 0,
      |	"reduce_in_money": 0,
      |	"platform_money_in": 0,
      |	"platform_money_out": 0
      |}
    """.stripMargin

  val OWNER_ALL =
    """
      |{
      |"app_code": "redbonus",
      |"owner_code": "",
      |"create_date": "2018-10-24 00:00:00",
      |"id": "e282e0d70d020809fc44f2d6070a6739"
      |}
    """.stripMargin


  val SK_REDBONUS=
    """
      |{
      |"id": -1,
      |"user_id": -1,
      |"chatg_id": -1,
      |"bill_id": 0,
      |"money": 0,
      |"total": 0,
      |"type": 0,
      |"ip": "172.31.214.244",
      |"create_time": "0000-00-00 00:00:00",
      |"version": 0,
      |"unique_id": "",
      |"app_code": "redbonus",
      |"owner_code": "",
      |"event_code": "sk_redbonus"
      |}
    """.stripMargin

  val SK_BILL_RECHARGE=
    """
      |{
      |"id": -1,
      |"user_id": -1,
      |"billt_id": -1,
      |"money": 0,
      |"money_before": 0,
      |"money_after": 0,
      |"intro": "",
      |"create_time": "0000-00-00 00:00:00",
      |"biz_id": 5152665,
      |"unique_id": "",
      |"app_code": "redbonus",
      |"owner_code": "",
      |"event_code": "sk_bill"
      |}
    """.stripMargin

  val SK_REDBONUS_GRAB=
    """
      |{
      |"id": -1,
      |"user_id": -1,
      |"redb_id": -1,
      |"bill_id": 0,
      |"money": 0,
      |"order": -1,
      |"create_time": "0000-00-00 01:51:57",
      |"unique_id": "pigss_2486652",
      |"app_code": "redbonus",
      |"owner_code": "",
      |"event_code": "sk_redbonus_grab"
      |}
    """.stripMargin
}
